name: very_good_ranch
description: A Very Good Flame game
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flame: ^1.3.0
  flame_behaviors: ^0.1.1
  flame_bloc: ^1.7.0
  flame_steering_behaviors:
    git: https://github.com/VeryGoodOpenSource/flame_steering_behaviors.git
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: 9.0.0-dev.3
  intl: ^0.17.0
  ranch_components:
    path: packages/ranch_components
  ranch_flame:
    path: packages/ranch_flame
  ranch_sounds:
    path: packages/ranch_sounds
  ranch_ui:
    path: packages/ranch_ui

dev_dependencies:
  bloc_test: ^9.1.0
  flame_test: ^1.3.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0-dev.1
  mocktail: ^0.3.0
  very_good_analysis: 3.0.2


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
